name: Heroku API Health Check

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual execution from GitHub Actions UI

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Heroku API
        id: check-api
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://baller-yuehcw-f6895eed5e61.herokuapp.com/)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "✅ API is healthy!"
            echo "status=healthy" >> $GITHUB_ENV
          else
            echo "❌ API is down! Response code: $RESPONSE"
            echo "status=down" >> $GITHUB_ENV
          fi

      - name: Log API Status
        run: |
          echo "API Status: ${{ env.status }}"
